# Build settings
title: [The title of your site]
description: [A short description of your site's purpose]

markdown: kramdown
markdown_ext: md
fenced_code_blocks: true
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
