# Build settings
title: (Just (Another (Build (System :for "Common Lisp"))))
description: NOT ONLY! A Build System

markdown: kramdown
markdown_ext: md
fenced_code_blocks: true
theme: jekyll-theme-slate
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
